# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/meital/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/meital/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meital/ClionProjects/MPCHonestMajorityNoTriples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meital/ClionProjects/MPCHonestMajorityNoTriples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/meital/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/meital/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ClionProjects/MPCHonestMajorityNoTriples/CMakeFiles /home/meital/ClionProjects/MPCHonestMajorityNoTriples/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ClionProjects/MPCHonestMajorityNoTriples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MPCHonestMajorityNoTriples

# Build rule for target.
MPCHonestMajorityNoTriples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MPCHonestMajorityNoTriples
.PHONY : MPCHonestMajorityNoTriples

# fast build rule for target.
MPCHonestMajorityNoTriples/fast:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/build
.PHONY : MPCHonestMajorityNoTriples/fast

HashEncrypt.o: HashEncrypt.cpp.o

.PHONY : HashEncrypt.o

# target to build an object file
HashEncrypt.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/HashEncrypt.cpp.o
.PHONY : HashEncrypt.cpp.o

HashEncrypt.i: HashEncrypt.cpp.i

.PHONY : HashEncrypt.i

# target to preprocess a source file
HashEncrypt.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/HashEncrypt.cpp.i
.PHONY : HashEncrypt.cpp.i

HashEncrypt.s: HashEncrypt.cpp.s

.PHONY : HashEncrypt.s

# target to generate assembly for a file
HashEncrypt.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/HashEncrypt.cpp.s
.PHONY : HashEncrypt.cpp.s

ProtocolParty.o: ProtocolParty.cpp.o

.PHONY : ProtocolParty.o

# target to build an object file
ProtocolParty.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolParty.cpp.o
.PHONY : ProtocolParty.cpp.o

ProtocolParty.i: ProtocolParty.cpp.i

.PHONY : ProtocolParty.i

# target to preprocess a source file
ProtocolParty.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolParty.cpp.i
.PHONY : ProtocolParty.cpp.i

ProtocolParty.s: ProtocolParty.cpp.s

.PHONY : ProtocolParty.s

# target to generate assembly for a file
ProtocolParty.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolParty.cpp.s
.PHONY : ProtocolParty.cpp.s

ProtocolTimer.o: ProtocolTimer.cpp.o

.PHONY : ProtocolTimer.o

# target to build an object file
ProtocolTimer.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolTimer.cpp.o
.PHONY : ProtocolTimer.cpp.o

ProtocolTimer.i: ProtocolTimer.cpp.i

.PHONY : ProtocolTimer.i

# target to preprocess a source file
ProtocolTimer.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolTimer.cpp.i
.PHONY : ProtocolTimer.cpp.i

ProtocolTimer.s: ProtocolTimer.cpp.s

.PHONY : ProtocolTimer.s

# target to generate assembly for a file
ProtocolTimer.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ProtocolTimer.cpp.s
.PHONY : ProtocolTimer.cpp.s

TemplateField.o: TemplateField.cpp.o

.PHONY : TemplateField.o

# target to build an object file
TemplateField.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/TemplateField.cpp.o
.PHONY : TemplateField.cpp.o

TemplateField.i: TemplateField.cpp.i

.PHONY : TemplateField.i

# target to preprocess a source file
TemplateField.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/TemplateField.cpp.i
.PHONY : TemplateField.cpp.i

TemplateField.s: TemplateField.cpp.s

.PHONY : TemplateField.s

# target to generate assembly for a file
TemplateField.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/TemplateField.cpp.s
.PHONY : TemplateField.cpp.s

ZpKaratsubaElement.o: ZpKaratsubaElement.cpp.o

.PHONY : ZpKaratsubaElement.o

# target to build an object file
ZpKaratsubaElement.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ZpKaratsubaElement.cpp.o
.PHONY : ZpKaratsubaElement.cpp.o

ZpKaratsubaElement.i: ZpKaratsubaElement.cpp.i

.PHONY : ZpKaratsubaElement.i

# target to preprocess a source file
ZpKaratsubaElement.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ZpKaratsubaElement.cpp.i
.PHONY : ZpKaratsubaElement.cpp.i

ZpKaratsubaElement.s: ZpKaratsubaElement.cpp.s

.PHONY : ZpKaratsubaElement.s

# target to generate assembly for a file
ZpKaratsubaElement.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/ZpKaratsubaElement.cpp.s
.PHONY : ZpKaratsubaElement.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MPCHonestMajorityNoTriples.dir/build.make CMakeFiles/MPCHonestMajorityNoTriples.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MPCHonestMajorityNoTriples"
	@echo "... HashEncrypt.o"
	@echo "... HashEncrypt.i"
	@echo "... HashEncrypt.s"
	@echo "... ProtocolParty.o"
	@echo "... ProtocolParty.i"
	@echo "... ProtocolParty.s"
	@echo "... ProtocolTimer.o"
	@echo "... ProtocolTimer.i"
	@echo "... ProtocolTimer.s"
	@echo "... TemplateField.o"
	@echo "... TemplateField.i"
	@echo "... TemplateField.s"
	@echo "... ZpKaratsubaElement.o"
	@echo "... ZpKaratsubaElement.i"
	@echo "... ZpKaratsubaElement.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

